### ISSUE TITLE
[BUG?] Problem installing petry via mise.  

### ISSUE THREAD

**Issue by tracure1337** [mise-plugins/mise-poetry#11]
Any other tool works without any problems.

![image](https://github.com/mise-plugins/mise-poetry/assets/43231640/6aceca77-081b-4ab1-b9e2-6aaa6d1ead6a)

![image](https://github.com/mise-plugins/mise-poetry/assets/43231640/5c887aa0-1f45-486b-be5a-fd4dcc0bf3b3)

![image](https://github.com/mise-plugins/mise-poetry/assets/43231640/9117d0bf-4e73-4d6b-8c33-9c2cb596badc)

![image](https://github.com/mise-plugins/mise-poetry/assets/43231640/3fc2b641-63ec-48f4-a3ba-d75c3001bed9)

![image](https://github.com/mise-plugins/mise-poetry/assets/43231640/182c21f2-1e78-4c58-a272-dfeb0c5c3e28)

it clearly cannot find the venv for the python that poetry intends to use.  
But do I actually want it to use that ? Why not use the mise installed python version. 

What I tried:  (just with /.local/share/mise/installs/python/3.11.8/lib of course, not with 3.11.7 as indicated from the screenshots.

![image](https://github.com/mise-plugins/mise-poetry/assets/43231640/8632a548-4cdb-40be-b31a-18e290ab8eb2)

Any ideas :-) ? 

Thank you for taking the time.

**Comment by tracure1337** [comment]
Is more information needed to be able to fix this?
I completely reinstalled mise but it still does not work unfrotunately.

**Comment by jdx** [comment]
#9
