### ISSUE TITLE
Silence warning that venv does not exist

### ISSUE THREAD

**Issue by SteffenMuehle** [mise-plugins/mise-poetry#23]
I work in a monorepo that has one `.tool-versions` file at its root and several subfolders that are Python projects with `pyproject.toml`s in them, all thus using the same tool-versions, which works fine.

However, when entering the repo in a new terminal, I get a one-time (once per terminal session) warning:
`mise-poetry: Virtualenv does not exist at . Execute `poetry install` to create one.` .

As I intentionally do not have a .venv in my repo root, I would like to silence this warning.
How can I do that?

---

.tool-versions file:
```
python 3.12.7
poetry 1.8.4
```

mise version:
`2024.11.27 linux-x64 (5562f2f 2024-11-23)`

OS:
Ubuntu 24.04.1 LTS

**Comment by gzurowski** [comment]
I am seeing the same behavior on my end. A couple of recent changes introduces these error message, see the following initial issue for more context: https://github.com/mise-plugins/mise-poetry/issues/21

Is it possible to have Poetry defined as a global tool and not see these message @chris-lingwood-korelabs-co? 

My global mise configuration has the following entry:
```
poetry = "latest"
```

**Comment by chris-lingwood-korelabs-co** [comment]
The bug I fixed (at the second attempt I hope) was that auto install didn't work and it exited too soon so this code didn't run. By the sounds of it its exiting for the right reasons now, but the message is just...pointless.

Do you think the code path is wrong or that the message is just annoying?

I'd not disagree, but I really don't want to become the defactor maintainer of this and it _sounds_ like its working as designed.

**Comment by gzurowski** [comment]
I think the fix is fine, I am mainly referring to the annoying messages. Do you think we can remove these messages?

**Comment by chris-lingwood-korelabs-co** [comment]
I don't see the rational for the message. Auto install is documented (and now works ;) ) and if you don't want that, being spammed isn't a good alternative. Devs will already know they need to run poetry install, thats how poetry works, its the normal state.
