### ISSUE TITLE
Poetry Install Issues with mise (Related to symlink and python3.*dylib missing)

### ISSUE THREAD

**Issue by ethunk** [mise-plugins/mise-poetry#9]
I kept running into issues for installing Poetry using mise. 

### Local Setup To Reproduce
System: Mac OS (M1)

.tool-versions file:
```
poetry 1.6.1
```

Command to install and output:
```bash
mise install poetry 1.6.1 --verbose
[DEBUG] ARGS: /Users/<>/.local/bin/mise install poetry 1.6.1 --verbose
[DEBUG] Config {
    Config Files: [
        "~/.config/mise/config.toml",
        "~/.tool-versions",
    ],
}
[DEBUG] Toolset: go@1.21.5, python@3.11.6, rust@1.74.1
installing
~/.local/share/mise/plugins/poetry/bin/install
[DEBUG] $ ~/.local/share/mise/plugins/poetry/bin/install
Retrieving Poetry metadata
# Welcome to Poetry!
This will download and install the latest version of Poetry,
a dependency and package manager for Python.
It will add the `poetry` command to Poetry's bin directory, located at:
/Users/<>/.local/share/mise/installs/poetry/1.6.1/bin
You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.
Installing Poetry (1.6.1)
Installing Poetry (1.6.1): Creating environment
Installing Poetry (1.6.1): An error occurred. Removing partial environment.
Poetry installation failed.
See /Users/<>/MI/poetry-installer-error-9usoojv5.log for error logs.
Cleanup: Something went wrong!
47 /Users/<>/.local/share/mise/plugins/poetry/bin/install: POETRY_HOME=$install_path python3 - --version "$version" $flags
[ERROR] ~/.local/share/mise/plugins/poetry/bin/install failed
Error:
   0: ~/.local/share/mise/plugins/poetry/bin/install exited with non-zero status: exit code 250

Location:
   /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/convert/mod.rs:757

Version:
   2024.2.2 macos-arm64 (1f11a1d 2024-02-02)

Suggestion: Run with --verbose or MISE_VERBOSE=1 for more information.

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Looking at the log file produced by poetry: 
```bash
cat /Users/<>/MI/poetry-installer-error-9usoojv5.log
dyld[32665]: Library not loaded: @executable_path/../lib/libpython3.11.dylib
  Referenced from: <EC57C3BD-D6B2-3EC2-8C9E-F9D225344939> /Users/ehunkler/.local/share/mise/installs/poetry/1.6.1/venv/bin/python3
  Reason: tried: '/Users/ehunkler/.local/share/mise/installs/poetry/1.6.1/venv/lib/libpython3.11.dylib' (no such file)

Traceback:

  File "<stdin>", line 923, in main
  File "<stdin>", line 562, in run
```

I googled a bunch and found this helpful thread: https://github.com/python-poetry/install.python-poetry.org/issues/24

The solution I found to fix this issue is I manually updated on my local machine the install script for poetry located here:

`~/.local/share/mise/plugins/poetry/bin/install`

and changed the install script to have the `sed 's/symlinks=False/symlinks=True/'` command. 

```
  if [ "$install_type" = "version" ]; then
    curl -sSL "$install_url" | sed 's/symlinks=False/symlinks=True/' | POETRY_HOME=$install_path python3 - --version "$version" $flags
  elif [ "$install_type" = "ref" ]; then
    curl -sSL "$install_url" | sed 's/symlinks=False/symlinks=True/' | POETRY_HOME=$install_path python3 - --git https://github.com/python-poetry/poetry.git@"$version" $flags
  else
    fail "unknown install type"
  fi
```

After these changes, the command worked for me and I was able to install poetry again with mise.

**Comment by jdx** [comment]
I wonder if this is related to #6 and if this fixes that issue with precompiled binaries. If so, we might want to think about how to incorporate this patch into the plugin

**Comment by jylenhofdecat** [comment]
The provided fix indicated here helped me to correctly install poetry via mise for me too. Perhaps time to push a fix in the plugin ?

**Comment by gzurowski** [comment]
I also ran into the exact same issue and the workaround described by @ethunk fixed it for me. It would be great to incorporate this upstream.

**Comment by cobyism** [comment]
+1 also ran into this exact issue. Fix described by @ethunk allowed install to work. Thanks! 💟 

- System: Mac OS (M2)
- Poetry v1.8.2

**Comment by sjpalf** [comment]
In case this helps anyone, based on the fix above I added the following to my Dockerfile to get `mise install poetry` working (on `debian:bookworm-slim`)
```
RUN sed -i 's@curl -sSL "$install_url" |@curl -sSL "$install_url" | sed '\''s/symlinks=False/symlinks=True/'\'' |@g' ~/.local/share/mise/plugins/poetry/bin/install
```

**Comment by ducdetronquito** [comment]
Thanks for the fix @ethunk : works like a charm now !

EDIT: Hard to sell to my coworkers, but enough to let me play with mise :)

(Ubuntu 22.04, Python 3.11.8, poetry 1.7.1)

**Comment by jdx** [comment]
This is biting a lot of people and it's a bad issue. If we're not able to get a fix in, it would be really good for us to have some sort of warning or something, unfortunately it's not easy to detect and there really isn't anything I think we could do when poetry is actually executed. It's probably equally problematic even if users. I have tried to see if I can fix this so poetry just works but I really have no idea what needs to change in order to fix it unfortunately.

Maybe in the short term to stop the bleeding, would someone mind modifying this warning to specifically call out poetry? Maybe be super loud if we notice the user is also using the poetry plugin? https://github.com/jdx/mise/blob/main/src/plugins/core/python.rs#L139

**Comment by andersfylling** [comment]
What are the blockers for introducing the fix by @ethunk?

I had to do the same for my linux system.

**Comment by jdx** [comment]
oh right, I forgot about that, I suppose we can try it
